print("I'm learning Git merge conflicts")
name = input('Please enter your name: ')
last_name = input('Please enter your last name: ')
nick = input('Please enter your nickname: ')
print(f'Hi, {name} {last_name} a.k.a. {nick}!')